# Generated by Mason CLI
# Author: {{ author_name }}

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
ENVIRONMENT = "development"
APP_NAME = "{{ project_name }}"

DATABASE = {
    "ENGINE": "sqlite",
    "NAME": BASE_DIR / "db.sqlite3",
}
